### ISSUE TITLE
Can't handle multiple heaters (limited to only first heater)

### ISSUE THREAD

**Issue by prier4ever** [zxdavb/incomfort-client#4] opened 2019-10-29 07:43 UTC
I have more than one heater but only one is shown in Home Assistant, the heater with climate control is not showing. It only gets the heater 0 , is it possible to select heater 1 instead of 0.

```
[2019-10-29 07:31:22 DEBUG (MainThread) [incomfortclient] Gateway(hostname=10.0.0.249) instantiated.
2019-10-29 07:31:22 DEBUG (MainThread) [incomfortclient] _get(url=heaterlist.json, auth=None)
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] _get(url=heaterlist.json): response = {'heaterlist': ['********728', '********429', None, None, None, None, None, None]}
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] Heater(serial_no=********728) instantiated.
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] Heater(serial_no=********429) instantiated.
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] _get(url=data.json?heater=0, auth=None)
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] _get(url=data.json?heater=0): response = {'nodenr': 162, 'ch_temp_lsb': 165, 'ch_temp_msb': 25, 'tap_temp_lsb': 105, 'tap_temp_msb': 16, 'ch_pressure_lsb': 150, 'ch_pressure_msb': 0, 'room_temp_1_lsb': 255, 'room_temp_1_msb': 127, 'room_temp_set_1_lsb': 255, 'room_temp_set_1_msb': 127, 'room_temp_2_lsb': 255, 'room_temp_2_msb': 127, 'room_temp_set_2_lsb': 255, 'room_temp_set_2_msb': 127, 'displ_code': 126, 'IO': 0, 'serial_year': 19, 'serial_month': 5, 'serial_line': 15, 'serial_sn1': 0, 'serial_sn2': 97, 'serial_sn3': 28, 'room_set_ovr_1_msb': 0, 'room_set_ovr_1_lsb': 0, 'room_set_ovr_2_msb': 0, 'room_set_ovr_2_lsb': 0, 'rf_message_rssi': 31, 'rfstatus_cntr': 0}
2019-10-29 07:31:23 DEBUG (MainThread) [incomfortclient] Heater(********728).status() = {'display_code': 126, 'display_text': 'standby', 'fault_code': None, 'is_burning': False, 'is_failed': False, 'is_pumping': False, 'is_tapping': False, 'heater_temp': 65.65, 'tap_temp': 42.01, 'pressure': 1.5, 'serial_no': '********728', 'nodenr': 162, 'rf_message_rssi': 31, 'rfstatus_cntr': 0}](url)
```

**Comment by zxdavb** [comment] 2019-10-29 08:01
Sure. We can do this: can I check you have no need for multiple heaters, and that you only need to choose which heater?

**Comment by zxdavb** [comment] 2019-10-29 08:06
... can you open this issue at HAs repo? The problem is over there - it makes it easier for everyone.

**Comment by prier4ever** [comment] 2019-10-29 08:06
Multiple heaters to show up would be nice, the selection is more a workaround

**Comment by prier4ever** [comment] 2019-10-29 08:20
> 
> 
> ... can you open this issue at HAs repo? The problem is over there - it makes it easier for everyone.

Done

Incomfort - Multiple heaters problem #28318

**Comment by zxdavb** [comment] 2019-10-29 10:29
Closing this here as it is not an issue with this code.

**Comment by zxdavb** [comment] 2019-10-29 13:23
Re-opening, as this functionality _will_ require a change in this code after all.

**Comment by zxdavb** [comment] 2019-10-29 20:58
PR pushed. Resolved.

**Closed by zxdavb** 2019-10-29 20:58 UTC
